### PR TITLE
修复oauth回调回来后nickname默认值

### PR DESCRIPTION
**Pull request by gm-fire**
**Fixes 用户设置nickname的默认值**

**Changes proposed in this pull request:**
js/src/forum/index.js

**Reviewers should focus on:**

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

### CODE REVIEW

**Comment by luceos** [comment]
@gm-fire without proper clarification why this change is needed we cannot review it. I tried looking into it, but the value you've changed seemed to only set a default for the SignupModal. Your edit, as such, does not seem to have any purpose. Please clarify.

**Comment by gm-fire** [comment]
> @gm-fire without proper clarification why this change is needed we cannot review it. I tried looking into it, but the value you've changed seemed to only set a default for the SignupModal. Your edit, as such, does not seem to have any purpose. Please clarify.

你好,是这样的,因为当我打开注册允许设置nickname的时候,我设置了一个对应的默认值,但是SignupModal里面却显示username的值,这样username和nickname就完全一样了,我认为这是不对的.

**Comment by luceos** [comment]
No it is not wrong. It is a default. The user can decide for themselves to change it.

Closing.

**Comment by gm-fire** [comment]
> No it is not wrong. It is a default. The user can decide for themselves to change it.
> 
> Closing.

如果设置了默认值,用户并不能修改它.比如我使用了 passport 去注册一个新用户.部分代码如下

image


最后出现的情况就是我设置的nickname默认值被改为username, 而且在SignupModal禁止我重新修改nickname.请看以下代码

image

所以我才修改并提交了我的代码

**Comment by gm-fire** [comment]
https://github.com/flarum/nicknames/assets/5047482/3994e990-a853-470a-ad33-bc01b6972026

@luceos 在视频可以看到用户是无法修改它,我的修改就是为了获取正确的nickname,如下图

image

不知道这样是否能清楚说明我的修改意图

**Comment by xfoxfu** [comment]
With OAuth / Passport extension, when the user signup via SSO, it is possible to **provide** values to the signup form, and the `provide`-d values are not changeable, like the username or email. However, in _Nicknames_ extension, it does not respect the existing behavior over `provide` (it is not modifiable, but does not use the provided value), which I believe should be a bug.

```php
$registration
    ->provideTrustedEmail($email)
    ->provide('username', $user->getId() ?: '')
    ->provide("nickname", $user->getName() ?: $user->getEmail())
    ->setPayload($user->toArray());
```

The code above results in the username and email being unmodifiable, as well as the nickname, but the nickname does not use the provided value, but instead, it uses username. This is inconsistent.

Built-in fields:

```js
// SignUpModal
this.username = Stream(this.attrs.username || '');

isProvided(field: string): boolean {
  return this.attrs.provided?.includes(field) ?? false;
}

items.add(
  'username',
  <div className="Form-group">
    <input
      className="FormControl"
      name="username"
      type="text"
      placeholder={usernameLabel}
      aria-label={usernameLabel}
      bidi={this.username}
      disabled={this.loading || this.isProvided('username')}
    />
  </div>,
  30
);
```

Nickname:

```js
this.nickname = Stream(this.attrs.username || '');

items.add(
  'nickname',
  <div className="Form-group">
    <label>{app.translator.trans('flarum-nicknames.forum.edit_user.nicknames_heading')}</label>
    <input
      className="FormControl"
      placeholder={extractText(app.translator.trans('flarum-nicknames.forum.edit_user.nicknames_text'))}
      bidi={this.nickname}
    />
  </div>,
  100
);
```

I would suggest using the `provide`-d value as the first priority, and if it does not exist, use `username` as a fallback, to make the behavior consistent.

**Pull request closed without merging**
